"""empty message

Revision ID: 9564d315d790
Revises: 
Create Date: 2020-09-01 21:06:44.169222

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9564d315d790'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('ip', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('images',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('port', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('worker_ip', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['worker_ip'], ['worker.ip'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('worker')
    # ### end Alembic commands ###
