"""Initial migration.

Revision ID: c68af084c9bb
Revises: 
Create Date: 2020-08-31 12:36:08.177852

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c68af084c9bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('worker',
    sa.Column('ip', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('ip')
    )
    op.create_table('images',
    sa.Column('id', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('host', sa.Text(), autoincrement=False, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('port', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('worker_ip', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['worker_ip'], ['worker.ip'], ),
    sa.PrimaryKeyConstraint('id', 'host')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    op.drop_table('worker')
    # ### end Alembic commands ###
