version: '3.1'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: orchestrus
    ports: 
        - "5432:5432"

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
        PGADMIN_DEFAULT_EMAIL: admin@linuxhint.com
        PGADMIN_DEFAULT_PASSWORD: secret
    ports:
        - "8080:80"
    volumes:
        - pgadmin-data:/var/lib/pgadmin

  # db_connexion:
  #   image: thebodyboutet/tp3_db_connexion
  #   restart: always
  #   depends_on: 
  #       - postgres
  #   environment:
  #     POSTGRES_HOST: postgres 
  #     POSTGRES_PORT: 5432
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: postgres
  #     POSTGRES_DB: orchestrus
  #   ports: 
  #       - "1234:1234"

  # orchestrus:
  #   image: thebodyboutet/tp3_orchestrus
  #   restart: always
  #   environment: 
  #       DB_CONNEXION_URL: http://db_connexion:1234
  #   ports: 
  #       - "1235:1235"

  # worker:
  #   image: thebodyboutet/tp3_worker
  #   restart: always
  #   ports: 
  #       - "5000:5000"
  #   volumes: 
  #       - /var/run/docker.sock:/var/run/docker.sock

  # client:
  #   image: thebodyboutet/tp3_client
  #   restart: always
  #   volumes:
  #       - './client/:/app'
  #       - '/app/node_modules'
  #   ports:
  #       - "3000:3000"
  #   stdin_open: true

volumes:
  postgres_data:
  pgadmin-data:
